### ISSUE TITLE
Datasets咨询

### ISSUE THREAD

**Issue by panyi95** [pengHTYX/OPAL#1]
您好，我想尝试使用您提供代码进行复现，
因为我就是简单的把HCI4D的数据集放上去进行复现，可是加载不上数据集，
可以release您使用的三个数据集嘛？
或者您简单的放一到两个数据集，这样我可以模仿。谢谢您
期待您的回复。

**Comment by Joey1998hub** [comment]
你好，我们已经更新了代码，请将格式为 .png 的HCI数据集放置在 ./dataset/hci_dataset 文件夹中，具体数据集处理操作可以参考 data_util.py 和 LFattdata.py 文件，数据集的具体格式可以参考下图：
![image](https://github.com/pengHTYX/OPAL/assets/50704613/8fe2e848-bfd8-4d45-a8c6-e77d5b27451b)
