### ISSUE TITLE
代码咨询

### ISSUE THREAD

**Issue by panyi95** [pengHTYX/OPAL#2]
if opt.display_id > 0:
   visualizer.plot_current_losses(epoch, float(epoch_iter) / dataset_size, losses)
您好，请问再您使用的train.py文件中的104行又这么一个代码，请问您使用的plot_curren_losses是一个什么样的程序呀，我在论文和代码中都没有找到。谢谢您的回复！

**Comment by Joey1998hub** [comment]
你好，我们已经更新了train.py文件

**Comment by panyi95** [comment]
![image](https://github.com/pengHTYX/OPAL/assets/67912231/2901c3bc-9d39-4e46-b43b-1dafdeb99674)
您好，感谢您的回复！我已经更新了代码进行了尝试。
您是否可以更新一下您的数据集是怎么处理的？我在运行的过程中出现了loss L1和smooth都为0的情况的，请问这样该如何处理呀？感谢

**Comment by Joey1998hub** [comment]
你好，我们已经更新了代码，请将格式为 .png 的HCI数据集放置在 ./dataset/hci_dataset 文件夹中，具体数据集处理操作可以参考 data_util.py 和 LFattdata.py 文件。
