### ISSUE TITLE
数据集咨询

### ISSUE THREAD

**Issue by haozhang09** [pengHTYX/OPAL#5]
# load invalid regions from training data (ex. reflective region)   
        boolmask_img4= imageio.imread(root + 'additional_invalid_area/kitchen/input_Cam040_invalid_ver2.png')
        boolmask_img6= imageio.imread(root + 'additional_invalid_area/museum/input_Cam040_invalid_ver2.png')
        boolmask_img15=imageio.imread(root + 'additional_invalid_area/vinyl/input_Cam040_invalid_ver2.png')
        self.boolmask_img4  = 1.0*boolmask_img4[:,:,3]>0
        self.boolmask_img6  = 1.0*boolmask_img6[:,:,3]>0
        self.boolmask_img15 = 1.0*boolmask_img15[:,:,3]>0
        请问从哪里可以获取这三张png?

**Comment by pengHTYX** [comment]
您好，在这个repo可以找到：
 https://github.com/LIAGM/LFattNet/tree/master/hci_dataset/additional_invalid_area

**Comment by haozhang09** [comment]
请问能否提供制作好的Real-World LF Datasets？

**Comment by Joey1998hub** [comment]
您好，在下面这个链接里面有Real-World LF Datasets
链接：https://pan.baidu.com/s/1zMJMHq3R2o4ioFyLgtvcVA?pwd=dsw3 
提取码：dsw3
